spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PostMatchSearch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Manjit@4678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # keep 'none' if DB is pre-created manually
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
